// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgvosdksuoudjxfawfgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhndm9zZGtzdW91ZGp4ZmF3Zmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODcwMDIsImV4cCI6MjA2ODY2MzAwMn0.SnU-Qtvdlq35lqetSyH77jAMh4S4ncFR-AKzqmeLkbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});